INSERT IGNORE INTO Skill (Skill) VALUES ('PETTING');
INSERT IGNORE INTO Skill (Skill) VALUES ('WALKING');
INSERT IGNORE INTO Skill (Skill) VALUES ('FEEDING');
INSERT IGNORE INTO Skill (Skill) VALUES ('MEDICATING');
INSERT IGNORE INTO Skill (Skill) VALUES ('SHAVING');

INSERT IGNORE INTO Weekday (weekday) VALUES ('MONDAY');
INSERT IGNORE INTO Weekday (weekday) VALUES ('TUESDAY');
INSERT IGNORE INTO Weekday (weekday) VALUES ('WEDNESDAY');
INSERT IGNORE INTO Weekday (weekday) VALUES ('THURSDAY');
INSERT IGNORE INTO Weekday (weekday) VALUES ('FRIDAY');
INSERT IGNORE INTO Weekday (weekday) VALUES ('SATURDAY');
INSERT IGNORE INTO Weekday (weekday) VALUES ('SUNDAY');