INSERT INTO Skill (Skill) VALUES ('PETTING');
INSERT INTO Skill (Skill) VALUES ('WALKING');
INSERT INTO Skill (Skill) VALUES ('FEEDING');
INSERT INTO Skill (Skill) VALUES ('MEDICATING');
INSERT INTO Skill (Skill) VALUES ('SHAVING');
